name: test
on:
  workflow_dispatch:
  push:
    paths:
      - "**.yml"
      - "**.sh"
  pull_request:
    paths:
      - "**.yml"
      - "**.sh"

defaults:
  run:
    shell: bash

jobs:
  test-cache:
    uses: ./.github/workflows/env.yml
    with:
      cache: true

  test-no-cache:
    uses: ./.github/workflows/env.yml
    with:
      cache: false

  test-latest:
      uses: ./.github/workflows/versions.yml
      with:
        version_label: "latest version"

  test-exact-with-prefix:
    uses: ./.github/workflows/versions.yml
    with:
      version: "v1.2.0"
      version_label: "exact v1.2.0 (with prefix)"
      version_check_pattern: "1.2.0"

  test-exact-no-prefix:
    uses: ./.github/workflows/versions.yml
    with:
      version: "1.2.0"
      version_label: "exact 1.2.0 (no prefix)"
      version_check_pattern: "1.2.0"

  test-fuzzy-minor-with-prefix:
    uses: ./.github/workflows/versions.yml
    with:
      version: "v1.1"
      version_label: "fuzzy v1.1 (minor)"
      version_check_pattern: "1.1."

  test-fuzzy-minor-no-prefix:
    uses: ./.github/workflows/versions.yml
    with:
      version: "1.1"
      version_label: "fuzzy 1.1 (minor, no prefix)"
      version_check_pattern: "1.1."

  test-fuzzy-major-with-prefix:
    uses: ./.github/workflows/versions.yml
    with:
      version: "v1"
      version_label: "fuzzy v1 (major)"
      version_check_pattern: "1."

  test-fuzzy-major-no-prefix:
    uses: ./.github/workflows/versions.yml
    with:
      version: "1"
      version_label: "fuzzy 1 (major, no prefix)"
      version_check_pattern: "1."

  test-exact-old-version:
    uses: ./.github/workflows/versions.yml
    with:
      version: "v1.0.0"
      version_label: "exact v1.0.0 (old version)"
      version_check_pattern: "1.0.0"
