name: test
on:
  workflow_dispatch:
  push:
    paths:
      - "**.yml"
  pull_request:
    paths:
      - "**.yml"

defaults:
  run:
    shell: bash

jobs:
  test-cache:
    uses: ./.github/actions/env.yml
  test-no-cache:
    uses: ./.github/actions/env.yml
    with:
      cache: "false"
